// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM86UC_S2LJ3oTTf-k8Ievl4yyP40o8ys',
    appId: '1:724199135505:web:214c1e37c453820feb54b0',
    messagingSenderId: '724199135505',
    projectId: 'ezom-c6d6a',
    authDomain: 'ezom-c6d6a.firebaseapp.com',
    storageBucket: 'ezom-c6d6a.appspot.com',
    measurementId: 'G-M90NK5160V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Nwc9WQvCkvPpiO8ZpizebjFKbCzHFm8',
    appId: '1:724199135505:android:585692bac76611c7eb54b0',
    messagingSenderId: '724199135505',
    projectId: 'ezom-c6d6a',
    storageBucket: 'ezom-c6d6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5U0557E1pdfwJ5sDVUNzPnIHEB2ea-Jk',
    appId: '1:724199135505:ios:4d0740891d63c54ceb54b0',
    messagingSenderId: '724199135505',
    projectId: 'ezom-c6d6a',
    storageBucket: 'ezom-c6d6a.appspot.com',
    iosBundleId: 'com.example.ezom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5U0557E1pdfwJ5sDVUNzPnIHEB2ea-Jk',
    appId: '1:724199135505:ios:629c57944d8f3a45eb54b0',
    messagingSenderId: '724199135505',
    projectId: 'ezom-c6d6a',
    storageBucket: 'ezom-c6d6a.appspot.com',
    iosBundleId: 'com.example.ezom.RunnerTests',
  );
}
